### ISSUE TITLE
Summoning from compendium issues

### ISSUE THREAD

**Issue by maxobremer** [trioderegion/warpgate#140]
Not an expert on this, but didn't see a issue here or in the closed issues when i searched for compendium.

Basically forward linking an issue that was discover with the module [Arbrons Summoning (5e)/fctt-summoner](https://github.com/arbron/fvtt-summoner) where [summoning from a compendium is blocked by a warp gate issue](https://github.com/arbron/fvtt-summoner/issues/11). Maybe something can be done about this to make it possible to summon from a compendium. 

If this isn't possible or isn't related to warp gate anyway, please close this issue and my apologise.

**Comment by relaytheory** [comment]
Issue is also found utilizing PF2e Animations with Advanced Macros.

![Screenshot_3](https://github.com/trioderegion/warpgate/assets/32248765/56044cf5-31d3-4901-8af4-4864256f360c)

**Comment by trioderegion** [comment]
As it stands, warpgate has no built-in support for spawning directly from a compendium, as it violates the relation between token and source actor.

Modules built on top of warpgate can work around this by first importing, or using a default actor and applying *all* compendium actor changes to it as an unlinked token. Since this creates a full copy of the actor embedded within the scene itself, it would be very easy to bloat your world to the point of non-operation. 

Due to this, there is an extremely low chance warpgate will ever support this intrinsically.
