### ISSUE TITLE
More crosshairs icon controls

### ISSUE THREAD

**Issue by trioderegion** [trioderegion/warpgate#23]
In lieu of #22, provide a way to further customize how the center icon is displayed.

Offset from center, size, background color (or no background). This could be used to emulate a line or square template by using an empty icon box or an arrow icon, respectively.

**Comment by Lazytron** [comment]
something like this is what I was imagining for this version for reference (with just the animation webm replacing the central icon):
https://www.screencast.com/t/zHJqOESOEN

**Comment by trioderegion** [comment]
Thanks, that's helpful. I'll see what I can do on that front.

**Comment by trioderegion** [comment]
This particular item would not cover that, no, this one is related to more customization of the icon preview during crosshairs placement.

You are, essentially asking for crosshairs to do `interval:  (token.data.width % 2) > 0 ? -1 : 1` by default?

**Comment by napolitanod** [comment]
Sorry for the delay. I think I was reading the 'offset from center' part of this ticket liberally. I was picturing more that the template would have the icon/source of selection in the top left hand corner rather than center as an option, so that, by interval, the selection would always be over full grids. I hadn't considered what you wrote above regarding the interval being set dynamically so I am going to try that :)
