### ISSUE TITLE
Error on opening actor sheet if there is no token for the actor

### ISSUE THREAD

**Issue by BadIdeasBureau** [trioderegion/warpgate#47]
On opening an actor sheet for an actor without a token, the following error happens:
![image](https://user-images.githubusercontent.com/36359784/148999106-80ace593-09e6-47c0-9fbc-70bc59c557b2.png)

No obvious symptom here other than the console error (though I presume if I had any mutations I wouldn't get the revert button - doing setup for game so don't have the time to deep dive debug it)

**Comment by trioderegion** [comment]
Ah, yea, that makes sense. I am considering expanding my "token centric" view of warpgate, since all of the mutation data is currently stored on the actor.

The error itself is just an oversight as to what type of document I am receiving when rendering the actor sheet. It is intended that the Revert button *never* shows on actors in the sidebar. The only wrinkle is with linked tokens, which could have the revert button on its header since its a "singleton".

Thank you for the report, and you are correct, there should be no side-effects. I will get this patched up soon as I can.
