### ISSUE TITLE
[Feature request] Apply a MIT License instead a GPL-3.0 License

### ISSUE THREAD

**Issue by p4535992** [trioderegion/warpgate#57]
It is possible to apply a MIT license instead a GPL-3.0 License ?

**Comment by trioderegion** [comment]
Anything is possible 😄 !

May I ask why? The intention of the GPL was to encourage use as a library, which (as far as I understand) does not impose licensing restrictions on the caller of it.

**Comment by trioderegion** [comment]
Nah, I don't see any request as "stupid" -- its a valid question. What you have laid out is my understanding as well. I will ask for comments on the League server, however. I used GPL such that the warpgate source cannot simply be repackaged and sold as closed source, or stripped down to use as piecemeal code due to its tightly interwoven nature.

If there are functions in warpgate that *should* be exposed that are *not*, that is simply a shortcoming on my part and will gladly expose pretty much any function of warpgate if there is a need for it.  The API is intentionally kept rather slim as the project is being developed so that I can make more wide sweeping changes "under the hood" without fear of breaking other modules as much.

**Comment by p4535992** [comment]
kk i think i can close this issue than.
