### ISSUE TITLE
Reverting mutations fails on flags that did not exist prior.

### ISSUE THREAD

**Issue by krbz999** [trioderegion/warpgate#58]
I ran into the following issue while making a mutation on a (linked) actor in D&D 5e:

- The mutation sets an actor's `token.actor.data.flags.dnd5e.weaponCriticalThreshold` flag to, e.g., 19, but then does not revert properly.
- The flag does not exist prior to the mutation (defaulting to 20).
- It stays 19 after reverting.

If the flag exists (set to 20) prior to the mutation, everything works as intended.

**Comment by trioderegion** [comment]
Is this with the latest version, 1.13.6? If not, I may have addressed that.

Otherwise, thank you for the report, I can potentially see how this would happen.

**Comment by krbz999** [comment]
My current version is 1.13.6, yes.

**Comment by trioderegion** [comment]
In the context of v2. Mutations will carry an object that describes the mutation stack that will be stored on the target document. With this in mind, the solution to this would be to "prime" the mutation stack entry with the manual data you want restored. 

Because a field present in an update doesnt exist on the document, its a bit tricky to remove it during the revert.

As implemented currently, you would add a callback to the `GEN_STACK_ENTRY` stage and modify the raw stack entry data to your liking.

I will investigate the feasibility of providing a method of "priming" of the mutation stack at creation time. In this context, you would be supplying a non-null value for the revert process - `20`

**Comment by trioderegion** [comment]
Closed by #83 

Update paths that do not exist in the original document being updated will now be stored with a `null` value and available in the delta callbacks for further modification.
